routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('company','CompanyController')->except('show');
    Route::resource('employee', 'EmployeeController')->except('show');
});

app/Company.php
<?php

namespace App;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Routing\UrlGenerator;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Company extends Model
{
    protected $appends = ['logo_url'];
    protected $fillable = [
      'name',
      'email',
      'logo',
      'website'
    ];

    /**
     * @return Application|UrlGenerator|string|null
     */
    public function getLogoUrlAttribute(){
        if(isset($this->attributes['logo'])) {
            return url(asset('storage/company/'.$this->attributes['logo']));
        }

        return null;
    }

    /**
     * @return HasMany
     */
    public function employees(){
        return $this->hasMany(Employee::class);
    }


}

app/Http/Controllers/Web/CompanyController.php
<?php

namespace App\Http\Controllers\Web;

use App\Company;
use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use Intervention\Image\Facades\Image;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $companies = Company::when($request->has('q'), static function(Builder $query) use ($request){
                return $query->where('name', 'like', '%'.$request->get('q').'%');
            })
            ->orderBy('id')
            ->paginate(5);
        return view ('companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'website' => 'required',
            'logo' => 'required|dimensions:min_width=100,min_height=200|mimes:png|max:2048'
        ]);

        $image = $request->file('logo');
        $images = time() . '.' . $image->getClientOriginalExtension();
        Image::make($image)->save(storage_path('app/public/company/' . $images));

        $input = [
           'name' => $request->get('name'),
           'email' => $request->get('email'),
           'website' => $request->get('website'),
           'logo' => $images
        ];

        $company = new Company();
        $company->fill($input);
        $company->save();

        return redirect()->route('company.index')
            ->with('success', 'Company data is successfully saved');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return Application|Factory|View
     */
    public function edit(Company $company)
    {
        return view('companies.edit', compact('company'));
    }


    /**
     * @param Request $request
     * @param Company $company
     * @throws ValidationException
     */
    public function update(Request $request, Company $company)
    {
        $rules = [
            'name' => 'required',
            'email' => 'required',
            'website' => 'required',
        ];
        if($request->has('logo')){
            $rules +=[
                'logo' => 'required|dimensions:min_width=100,min_height=200|mimes:png|max:2048'
            ];
        }
        $this->validate($request, $rules);

        $input = [
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'website' => $request->get('website')

        ];

        if($request->has('logo')) {
            $image = $request->file('logo');
            $images = time() . '.' . $image->getClientOriginalExtension();
            Image::make($image)->save(storage_path('app/public/company/' . $images));
            $input +=[
                'logo' => $images
            ];
        }

        $company->fill($input);
        $company->update();

        return redirect()->route('company.index')
            ->with('success', 'Company data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('company.index')
            ->with('success', 'Company data is successfully deleted');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br />
    @endif

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create Company Data</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif

                        <form method="POST" action="{{ route('company.store') }}" enctype="multipart/form-data" accept-charset="UTF-8">
                            @csrf
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" placeholder="name" required>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" name="email"  placeholder="email" required>

                            </div>
                            <div class="form-group">
                                <label>Logo</label><br/>
                                <input type="file" name="logo"  accept="image/png" placeholder="logo" onchange="loadFile(event)" required><br/>
                                <img id="output" width="200" />
                            </div>
                            <div class="form-group">
                                <label>Website</label>
                                <input type="text" class="form-control" name="website" placeholder="website" required>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endpush

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br />
    @endif

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Company Data</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif

                        <form method="POST" action="{{ route('company.update', $company) }}" enctype="multipart/form-data" accept-charset="UTF-8">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" value="{{ $company->name }}" name="name" placeholder="name" required>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" value="{{ $company->email }}" name="email"  placeholder="email" required>

                            </div>
                            <div class="form-group">
                                <label>Logo</label><br/>
                                <input type="file" name="logo" accept="image/png" placeholder="logo" onchange="loadFile(event)"><br/>
                                <img src="{{ $company->logo_url }}" id="output" width="200" />
                            </div>
                            <div class="form-group">
                                <label>Website</label>
                                <input type="text" value="{{ $company->website }}" class="form-control" name="website" placeholder="website" required>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        var loadFile = function(event) {
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
@endpush

resources/views/companies/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Management Company</div>
                @if(session()->get('success'))
                    <div class="alert alert-success"style="margin: 20px">
                        {{ session()->get('success') }}
                    </div><br />
                @endif
                <div class="card-body">
                    <a href="{{ route('company.create') }}" class="btn btn-primary">Add Data</a>
                    <div class="row" style="margin:20px">
                        <form class="row">
                            <div class="input-group hidden-xs" style="width: 150px;">
                                <input class="form-control" placeholder="{{ __('Search') }}&hellip;" name="q" value="{{ request('q') }}">
                            </div>
                        </form>
                    </div>
                    @if(!$companies->isEmpty())
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <td>ID</td>
                            <td>Logo</td>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Website</td>
                            <td width="150px">Action</td>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($companies as $company)
                        <tr>
                            <td>{{ $company->id }}</td>
                            <td>
                                <img src="{{ $company->logo_url }}" width="100px" height="100px" alt="{{ $company->logo }}">
                            </td>
                            <td>{{ $company->name }}</td>
                            <td>{{ $company->email }}</td>
                            <td>{{ $company->website }}</td>
                            <td>
                                <div class="btn-group">
                                    <a data-toggle="modal" data-target="#myModal{{ $company->id }}" class="btn btn-warning">Show</a>
                                    <!-- Modal -->
                                    <div id="myModal{{ $company->id }}" class="modal fade" role="dialog">
                                        <div class="modal-dialog">

                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                </div>
                                                <div class="modal-body">
                                                    <table class="table table-striped">
                                                        <thead>
                                                        <tr>
                                                            <td></td>
                                                            <td><img src="{{ $company->logo_url }}" width="200px" height="200px" alt="{{ $company->logo }}"></td>
                                                        </tr>
                                                        <tr>
                                                            <td><b>Name</b></td>
                                                            <td>{{ $company->name }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td><b>Email</b></td>
                                                            <td>{{ $company->email }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td><b>Website</b></td>
                                                            <td>{{ $company->website }}</td>
                                                        </tr>
                                                        </thead>
                                                    </table>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    <a href="{{ route('company.edit', $company->id)}}" class="btn btn-primary">Edit</a>
                                    <form action="{{ route('company.destroy', $company->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <center>{{ $companies->links() }}</center>
                    @else
                        <div class="px-3 text-center" style="padding: 10px">
                            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                                No Data
                            </p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection